### ISSUE TITLE
The absence of link in the Follow heading hierarchy

### ISSUE THREAD

**Issue by RinatValiullov** [fejes713/accessibility-guide#10]
I noticed that _Follow heading hierarchy_ section hasn't got any link in _Resources_
I think this resource will fit well: [Headings](https://www.w3.org/WAI/tutorials/page-structure/headings/)

**Comment by fejes713** [comment]
Hey @RinatValiullov, yes, some cards do not have recommended resources in them. Thanks for mentioning that article - I do agree it's helpful. 👍 

Would you like to try adding that by yourself ([see contribution guidelines](https://github.com/fejes713/accessibility-guide/blob/master/CONTRIBUTING.md)) or do you wan't me to quickly add that one?

**Comment by RinatValiullov** [comment]
> Would you like to try adding that by yourself ([see contribution guidelines](https://github.com/fejes713/accessibility-guide/blob/master/CONTRIBUTING.md)) or do you wan't me to quickly add that one?

Yeah sure, I will make PR about this section

**Comment by RinatValiullov** [comment]
@fejes713 
Can I close this issue after PR?

**Comment by fejes713** [comment]
Sure, `pro-tip`: You can include `resolves #10`in your commit message and PR will close the issue once merged 😉
