### ISSUE TITLE
Favicon missing

### ISSUE THREAD

**Issue by Link2Twenty** [fejes713/accessibility-guide#15]
I noticed you don't have a favicon, I threw something simple together. 

I think it looks ok scaled down to 16px too, feel free to use this image or use this issue as a place to talk about favicon ideas.

![favicon](https://user-images.githubusercontent.com/3534427/53741666-cc936280-3e8e-11e9-85a7-8b0c5f25b531.png)

**Comment by petrovicstefanrs** [comment]
#17 Resolved here
