### ISSUE TITLE
Terminology

### ISSUE THREAD

**Issue by hallmedia** [fejes713/accessibility-guide#18]
Actual: “Put a full stop at the end of the alt tag”
Expected: “Put a full stop at the end of the alt text”

Alt is an **attribute** that contains a text value – not a **tag** or an element.

**Comment by fejes713** [comment]
Hey, @hallmedia thanks for reporting this. 👍 

Would you perhaps like to make that modification following [guidelines](https://github.com/fejes713/accessibility-guide/blob/master/CONTRIBUTING.md)  or you want me to do it instead?

**Comment by fejes713** [comment]
fixed 👍 thanks for reporting.
