### ISSUE TITLE
Add http://accessible-colors.com to colors tip?

### ISSUE THREAD

**Issue by rpearce** [fejes713/accessibility-guide#7]
This is a really strong tool, as well.

<img width="869" alt="image" src="https://user-images.githubusercontent.com/592876/53458818-6aa4b880-3a9c-11e9-88fa-6f35ec568459.png">

http://accessible-colors.com/

**Comment by fejes713** [comment]
Yeah, this is a great tool as well. Feel free to open a PR, or if you don't have time, I can do so as well 😄
